# Options used by GitHub
# --pygments --no-lsi --safe
pygments: true
lsi: false
safe: true

# Exclude project-specific and source files when generating the site.
# TODO: Ignore .less files
exclude: docs/, lib/, scripts/

# "Watch" the site for changes and apply them automatically. 
auto: true

################################################################################
# Global variables used site-wide
################################################################################

project:
  name: Whispernote
  description: Create Evernote notes <br/>from Kindle highlights
  download: https://github.com/mattnorris/whispernote/raw/master/src/whispernote.py
  fork: https://github.com/mattnorris/whispernote

author:
  name: Matt Norris
  site: http://mattnorris.me
  email: matthew.g.norris@gmail.com
  github: mattnorris
  twitter: mattnorrisme
  linkedin: mattnorrisme

image: assets/img/whispernote-github-banner.jpg
navbar: false
